### ISSUE TITLE
Limba fails to build on Fedora 22

### ISSUE THREAD

**Issue by omega13a** [ximion/limba#12]
When trying to build on Fedora 22, I get the following useless error message:

CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:80 (pkg_check_modules)

**Comment by ximion** [comment]
I was able to build it just fine on Fedora 22 - could you run cmake again and attach the non-verbose log?
Apparently, a dependency of Limba is missing, which just needs to be installed to make it work.

**Comment by ximion** [comment]
Closing this issue, since it is missing details, and the build process works well in a fresh Fedora VM as well as on the CI.
Feel free to reopen if this happens again (but please paste a full log in that case).
