### ISSUE TITLE
Package installation broken with custom umask

### ISSUE THREAD

**Issue by jpumc** [ximion/limba#15]
Setting umask to `027` before installation makes the installed limba package unusable. Installed package directory in `/opt/software` has permissions `750`.

**Comment by ximion** [comment]
You did install Limba manually from Git, right? Or did you use any distribution packages?
(this issue should be rather trivial to be fixed - it should already work if the CLI tool is executed withour root previleges, which triggers it to run a small DBus daemon to perform privileged operations in a clean environment)

**Comment by jpumc** [comment]
Installed from Debian package - version 0.5.4.

`limba install` as normal user asks for password and works
`sudo limba install[-local]` is broken
`sudo limba refresh` is broken

**Comment by ximion** [comment]
This bug should be fixed with that commit, can you please verify if it works for you too?
Thanks for reporting it!

**Comment by jpumc** [comment]
Installed packages are now usable, but the `control`, `exported` and runtime files are user and group writable (the default umask is usually 0022 not 0002).

**Comment by ximion** [comment]
Urgh, you're right - that was unintentional, I corrected the setting now.
Thanks for noticing!
